# BungeeGuard+ Configuration

# Allowed authentication tokens.
allowed-tokens:
  - "YOUR_TOKEN"

# Messages

# Kick message sent to connections without any forwarded data from the proxy.
# Most likely a vanilla client connecting directly to the server, bypassing the proxy.
no-data-kick-message:
  - '&cTo configure BungeeGuard+ access the tutorial below:'
  - '&bhttps://docs.nickuc.com/bungeeguard'

# Kick message sent to connections with forwarding data, but without a correct BungeeGuard token
# included in their handshake. Assuming BungeeGuard is installed correctly on all proxies,
# this is most likely a client trying to exploit the BungeeCord protocol to spoof their uuid.
invalid-token-kick-message:
  - '&cThe BungeeGuard+ token sent by proxy server is not allowed by this backend server.'
  - ''
  - '&cTo configure BungeeGuard+ access the tutorial below:'
  - '&bhttps://docs.nickuc.com/bungeeguard'
